- name: Install Solr SystemD service
  ansible.builtin.template:
    src: etc/systemd/system/service.j2
    dest: /etc/systemd/system/{{ solr_service_name }}.service
    mode: "0644"
  register: _solr_systemd_service
  notify: restart solr
  vars:
    _service_config: >-
      {{
        solr_service_configuration | combine(
          solr_group_service_configuration,
          solr_host_service_configuration,
          list_merge=solr_service_configuration_list_merge,
          recursive=solr_service_configuration_recursive_merge
        )
      }}

- name: Install Solr environment file
  ansible.builtin.template:
    src: etc/default/environment.j2
    dest: "{{ solr_environment_file }}"
    owner: "{{ solr_environment_file_owner | d(omit) }}"
    group: "{{ solr_environment_file_group | d(omit) }}"
    mode: "{{ solr_environment_file_mode | d('0644') }}"
  notify:
    - restart solr
    - wait for solr to start
  vars:
    _environment_vars: >-
      {{
        solr_environment | combine(
          solr_group_environment,
          solr_host_environment
        )
      }}

- name: Install Solr configuration file
  ansible.builtin.template:
    src: "etc/solr/file.j2"
    dest: "{{ solr_configuration_file }}"
    owner: "{{ item.value.owner | d(omit) }}"
    group: "{{ item.value.group | d(omit) }}"
    mode: "{{ item.value.mode | d('0644') }}"
    backup: "{{ item.value.backup | d(omit) }}"
  vars:
    item:
      value: "{{ solr_configuration }}"

- name: Install Solr configuration files
  ansible.builtin.template:
    src: "etc/solr/file.j2"
    dest: "{{ solr_configuration_directory }}/{{ item.key }}"
    owner: "{{ item.value.owner | d(omit) }}"
    group: "{{ item.value.group | d(omit) }}"
    mode: "{{ item.value.mode | d('0644') }}"
    backup: "{{ item.value.backup | d(omit) }}"
  loop: "{{ _solr_configuration_files | dict2items }}"
  notify:
    - restart solr
    - wait for solr to start
  vars:
    _solr_configuration_files: >-
      {{
        solr_configuration_files | combine(
          solr_group_configuration_files,
          solr_host_configuration_files,
          recursive=True
        )
      }}

- name: Install Solr security configuration
  ansible.builtin.template:
    src: "var/lib/solr/security.json.j2"
    dest: "{{ solr_security_file }}"
    owner: "{{ solr_security_file_owner | d(omit) }}"
    group: "{{ solr_security_file_group | d(solr_user_group) }}"
    mode: "{{ solr_security_file_mode | d('0640') }}"
    backup: "{{ solr_security_file_backup | d(omit) }}"
  register: _solr_security_file
  vars:
    _solr_security_configuration: >-
      {{
        solr_security_configuration | combine(
          solr_group_security_configuration,
          solr_host_security_configuration,
          recursive=True
        )
      }}
        )
      }}

- name: Enable Solr service
  ansible.builtin.systemd:
    name: "{{ solr_service_name }}"
    enabled: "{{ solr_service_enabled | bool }}"
    state: "{{ solr_service_state | d(omit) }}"
    daemon_reload: "{{ _solr_systemd_service | d() is changed }}"
  ignore_errors: "{{ ansible_check_mode }}"
