---
- name: Install Solr
  ansible.builtin.import_tasks: installation.yml
  tags:
    - solr::install

- name: Configure Solr
  ansible.builtin.import_tasks: configuration.yml
  tags:
    - solr::configure

- name: Configure SolrCloud
  ansible.builtin.import_tasks: cloud.yml
  tags:
    - solr::configure
    - solr::cloud
  when: solr_cloud | bool

- name: Configure Solr Prometheus exporter
  ansible.builtin.import_tasks: exporter.yml
  tags:
    - solr::configure
    - solr::exporter
  when: solr_exporter_enabled | bool
