---
- name: Verify
  hosts: solr_servers
  gather_facts: false
  tasks:
    - name: Ensure Solr service is started
      ansible.builtin.service:
        name: solr
        state: started
      register: result
      check_mode: true
      failed_when: result is changed

    - name: Ensure Solr collection health is green
      ansible.builtin.uri:
        url: http://localhost:8983/api/cluster
        body_format: json
        user: "{{ solr_api_username }}"
        password: "{{ solr_api_password }}"
      register: result
      changed_when: false
      failed_when: >-
        result.status != 200 or
        result.json is not defined or
        result.json.responseHeader.status != 0 or
        result.json.cluster.collections.techproducts.replicationFactor != 2 or
        result.json.cluster.collections.techproducts.shards | length != 2 or
        result.json.cluster.collections.techproducts.health != "GREEN"

    - name: Index techproducts data # noqa command-instead-of-shell run-once[task]
      ansible.builtin.shell: >-
        /opt/solr/releases/current/bin/post
        -c techproducts
        -u {{ solr_api_username }}:{{ solr_api_password }}
        /opt/solr/releases/current/example/exampledocs/*
      changed_when: true
      run_once: true

    - name: Ensure data has been indexed
      ansible.builtin.uri:
        url: http://localhost:8983/solr/techproducts/select?indent=on&q=*:*
        body_format: json
        user: "{{ solr_api_username }}"
        password: "{{ solr_api_password }}"
      register: result
      changed_when: false
      retries: 30
      delay: 1
      until:
        - result.status == 200
        - result.json is defined
        - result.json.responseHeader is defined
        - result.json.responseHeader.status == 0
        - result.json.response.numFound == 51

    - name: Ensure Solr password hash is correct
      ansible.builtin.command:
        argv:
          - grep
          - -q
          - IV0EHq1OnNrj6gvRCwvFwTrZ1+z1oBbnQdiVC3otuq0= Ndd7LKvVBAaZIF0QAVi1ekCfAJXr1GGfLtRUXhgrF8c=
          - /var/lib/solr/security.json
      changed_when: false

    - name: Ensure basic authentication is required
      ansible.builtin.uri:
        url: http://localhost:8983/solr/techproducts/admin/ping
        status_code:
          - 401
      changed_when: false

- name: Verify solr1
  hosts: solr1
  gather_facts: false
  tasks:
    - name: Ensure Solr Prometheus exporter service is started
      ansible.builtin.service:
        name: solr-exporer
        state: started
      register: result
      check_mode: true
      failed_when: result is changed

    - name: Ensure Solr Prometheus exporter is responding
      ansible.builtin.uri:
        url: http://localhost:8989/metrics
      register: result
      changed_when: false
      retries: 10
      delay: 1
      until: result.status == 200
