solr_jetty_host: 0.0.0.0
solr_url: "http://127.0.0.1:{{ solr_port }}"

solr_zk_chroot: /solr
solr_zk_hosts: "{{ groups['zookeeper_servers'] }}"

solr_cloud_leader: "{{ groups['solr_servers'] | first }}"

solr_password: SolrRocks
solr_password_salt: "{{ 'Ndd7LKvVBAaZIF0QAVi1ekCfAJXr1GGfLtRUXhgrF8c=' | b64decode }}"

solr_api_username: solr
solr_api_password: "{{ solr_password }}"

solr_group_environment:
  SOLR_AUTH_TYPE: basic
  SOLR_AUTHENTICATION_OPTS: "-Dbasicauth=solr:SolrRocks"

solr_properties:
  basicAuth.conf:
    httpBasicAuthUser: "{{ solr_api_username }}"
    httpBasicAuthPassword: "{{ solr_api_password }}"

solr_host_security_configuration:
  authentication:
    blockUnknown: true
    class: solr.BasicAuthPlugin
    credentials:
      solr: "{{ solr_password | solr_password_hash(salt=solr_password_salt) }}"
  authorization:
    class: solr.RuleBasedAuthorizationPlugin
    permissions:
      - name: security-edit
        role: admin
    user-role:
      solr: admin

solr_local_configuration_sets_directory: configsets
solr_configuration_sets:
  techproducts:
    directory: techproducts

solr_collections:
  techproducts:
    name: techproducts
    config: techproducts
    replicationFactor: 2
    numShards: 2
